spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      indent_output: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}


